Models/Recognition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MIS4200_Team8.Models
{
    public class Recognition
    {
        public int recognitionID { get; set; }

        [Display(Name="Core value recognized")]
        [Range(1, 7, ErrorMessage = "Please select a core value from the dropdown")]
        public CoreValue award { get; set; }

        //Prefill to logged in employee
        [Display(Name = "Employee giving the recognition")]
        public Guid recognizor { get; set; }

        //Dropdown list of all registered employees
        [Display(Name = "Employee receiving the recognition")]
        public Guid recognized { get; set; }

        [Display(Name = "Date recognition given")]
        [Required(ErrorMessage = "A recognition date is required")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime recognitionDate { get; set; }

        [Display(Name = "Describe how this employee exemplified this core value")]
        public string descritption { get; set; }

        public enum CoreValue
        {
            Balance=1,
            Culture=2,
            [Display(Name = "Delivery Excellence")]
            DeliveryExcellence=3,
            [Display(Name = "Greater Good")]
            GreaterGood =4,
            Innovation=5,
            [Display(Name = "Integrity and Openness")]
            IntegrityAndOpenness =6,
            Stewardship=7
        }
               
        [ForeignKey("recognizor")]
        public virtual Profile employeeGiving { get; set; }

        [ForeignKey("recognized")]
        public virtual Profile employeeGetting { get; set; }
    }
}

Controllers/RecognitionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MIS4200_Team8.DAL;
using MIS4200_Team8.Models;

namespace MIS4200_Team8.Controllers
{
    public class RecognitionsController : Controller
    {
        private CentricContext db = new CentricContext();

        // GET: Recognitions
        [Authorize]
        public ActionResult Index(string searchString)
        {
            //var employeeSearch = from p in db.profile select p;
            var recognitionSearch = db.recognition.Include(e => e.employeeGetting).Include(e => e.employeeGiving);
            if (!String.IsNullOrEmpty(searchString))
            {
                recognitionSearch = recognitionSearch.Where(p => p.employeeGetting.lastName.Contains(searchString) || p.employeeGetting.firstName.Contains(searchString));
            }
            recognitionSearch = recognitionSearch.OrderByDescending(r => r.recognitionDate).Take(10);
            return View(recognitionSearch.ToList());

        }

        // GET: Recognitions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recognition recognition = db.recognition.Find(id);
            if (recognition == null)
            {
                return HttpNotFound();
            }
            return View(recognition);
        }

        // GET: Recognitions/Create
        public ActionResult Create()
        {
            string profileID = User.Identity.GetUserId();
            SelectList profiles = new SelectList(db.profile, "profileID", "fullName");
            profiles = new SelectList(profiles.Where(x => x.Value != profileID).ToList(), "Value", "Text");
            ViewBag.recognized = profiles;
            return View();

        }

        // POST: Recognitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "recognitionID,award,recognizor,recognized,recognitionDate,descritption")] Recognition recognition)
        {
            if (ModelState.IsValid)
            {
                Guid newProfileID;
                Guid.TryParse(User.Identity.GetUserId(), out newProfileID);
                recognition.recognizor = newProfileID;
                db.recognition.Add(recognition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            string profileID = User.Identity.GetUserId();
            SelectList profiles = new SelectList(db.profile, "profileID", "fullName");
            profiles = new SelectList(profiles.Where(x => x.Value != profileID).ToList(), "Value", "Text");
            ViewBag.recognized = profiles;

            //ViewBag.recognized = new SelectList(db.profile, "profileID", "fullName");
            return View(recognition);
        }

        // GET: Recognitions/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //string profileID = User.Identity.GetUserId();
            //SelectList profiles = new SelectList(db.profile, "profileID", "fullName");
            //profiles = new SelectList(profiles.Where(x => x.Value != profileID).ToList(), "Value", "Text");

            Recognition recognition = db.recognition.Find(id);
            if (recognition == null)
            {
                return HttpNotFound();
            }
            Guid recognitionID;
            Guid.TryParse(User.Identity.GetUserId(), out recognitionID);
            if (recognitionID == recognition.recognizor)
            {
                return View(recognition);
            }
            else
            {
                return View("notAuthorizedRecognition");
            }

        }

        // POST: Recognitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "recognitionID,award,recognizor,recognized,recognitionDate,descritption")] Recognition recognition)
        {

            if (ModelState.IsValid)
            {
                db.Entry(recognition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //string profileID = User.Identity.GetUserId();
            //SelectList profiles = new SelectList(db.profile, "profileID", "fullName");
            //profiles = new SelectList(profiles.Where(x => x.Value != profileID).ToList(), "Value", "Text");

            return View(recognition);
        }

        // GET: Recognitions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recognition recognition = db.recognition.Find(id);
            if (recognition == null)
            {
                return HttpNotFound();
            }
            //string profileID = User.Identity.GetUserId();
            //SelectList profiles = new SelectList(db.profile, "profileID", "fullName");
            //profiles = new SelectList(profiles.Where(x => x.Value != profileID).ToList(), "Value", "Text");

            return View(recognition);
        }

        // POST: Recognitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recognition recognition = db.recognition.Find(id);
            db.recognition.Remove(recognition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Recognitions/Create.cshtml
@model MIS4200_Team8.Models.Recognition

@{
    ViewBag.Title = "Create a Recognition";
}

<h2>Create a New Recognition</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.award, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.award, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.award, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.recognizor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.recognizor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.recognizor, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.recognized, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("recognized", (SelectList)ViewBag.recognized, "Please Select", htmlAttributes: new {@class = "form-control" })
            @Html.ValidationMessageFor(model => model.recognized, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.recognitionDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.recognitionDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.recognitionDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*<form action="/action_page.php">
            <textarea name="message" rows="10" cols="30"></textarea>
            <br><br>
            <input type="submit">
        </form>*@
        @Html.LabelFor(model => model.descritption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descritption, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descritption, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Recognitions/Delete.cshtml
@model MIS4200_Team8.Models.Recognition

@{
    ViewBag.Title = "Delete Recognition";
}

<h2>Delete Recognition Data</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.award)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.award)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognizor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeGiving.fullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognized)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeGetting.fullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognitionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recognitionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descritption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descritption)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
                    <div class="alert alert-danger">
            <strong>Danger!</strong> The action of deleting a recognition is irreversible.
        </div>
        </div>
    }
</div>

Views/Recognitions/Details.cshtml
@model MIS4200_Team8.Models.Recognition

@{
    ViewBag.Title = "Recognition Details";
}

<h2>Recognition Details</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.award)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.award)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognizor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeGiving.fullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognized)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeGetting.fullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognitionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recognitionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descritption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descritption)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.recognitionID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Recognitions/Edit.cshtml
@model MIS4200_Team8.Models.Recognition

@{
    ViewBag.Title = "Edit Recognition";
}

<h2>Edit Recognition</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
 
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.recognitionID)

    <div class="form-group">
        @Html.HiddenFor(model => model.recognizor)
        @Html.LabelFor(model => model.award, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.award, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.award, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.recognizor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">            
            @Html.EditorFor(model => model.employeeGiving.fullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.recognizor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.recognized, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.employeeGetting.fullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.recognized, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.recognitionDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.recognitionDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.recognitionDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descritption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descritption, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descritption, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Recognitions/Index.cshtml
@model IEnumerable<MIS4200_Team8.Models.Recognition>

@{
    ViewBag.Title = "Recognitions List";
}

<h2>10 Most Recent Recognitions</h2>

@using (Html.BeginForm("Index", "Recognitions", FormMethod.Get))
{
    <p>
        Find by employee name receiving recognition : @Html.TextBox("searchString")
        <input type="submit" value="Search" />
    </p>

}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.award)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognizor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognized)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognitionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descritption)
        </th>
        @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.award)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.employeeGiving.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.employeeGetting.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.recognitionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descritption)
            </td>
            @*<td>*@
                @*@Html.ActionLink("Edit", "Edit", new { id = item.recognitionID })*@
                @*@Html.ActionLink("Details", "Details", new { id = item.recognitionID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.recognitionID })*@
            @*</td>*@
        </tr>
    }

</table>

Views/Recognitions/notAuthorizedRecognition.cshtml
@{
    ViewBag.Title = "notAuthorizedRecognition";
}

<br />
<div class="alert alert-danger">
    <strong>Danger!</strong> You are not authorized to change a recognition that you did not give.
</div>

<br />
@Html.ActionLink("Back to List", "Index")