Controllers/NewProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MIS4200_Team8.DAL;
using MIS4200_Team8.Models;

namespace MIS4200_Team8.Controllers
{
    public class NewProfilesController : Controller
    {
        private CentricContext db = new CentricContext();

        // GET: NewProfiles
        [Authorize]
        public ActionResult Index(string searchString)
        {
            //var employeeSearch = from p in db.profile select p;
            var employeeSearch = db.profile.Include(e => e.employeeGetting).Include(e => e.employeeGiving);
            
            if (!String.IsNullOrEmpty(searchString))
            {
                employeeSearch = employeeSearch.Where(p => p.lastName.Contains(searchString) || p.firstName.Contains(searchString));
            }
             
            return View(employeeSearch.ToList());
        }

        // GET: NewProfiles/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.profile.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // GET: NewProfiles/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewProfiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "profileID,firstName,lastName,businessUnitLocation,hireDate,jobTitleName")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                //profile.profileID = Guid.NewGuid();
                Guid newProfileID;
                Guid.TryParse(User.Identity.GetUserId(), out newProfileID);
                profile.profileID = newProfileID;
                db.profile.Add(profile);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(profile);
        }

        // GET: NewProfiles/Edit/5
        [Authorize]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.profile.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            Guid profileID;
            Guid.TryParse(User.Identity.GetUserId(), out profileID);
            if (profileID == id)
            {
                return View(profile);
            }
            else
            {
                return View("notAuthorized");
            }
        }

        // POST: NewProfiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "profileID,firstName,lastName,businessUnitLocation,hireDate,jobTitleName")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: NewProfiles/Delete/5
        [Authorize]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.profile.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            Guid profileID;
            Guid.TryParse(User.Identity.GetUserId(), out profileID);
            if (profileID == id)
            {
                return View(profile);
            }
            else
            {
                return View("notAuthorized");
            }
        }

        // POST: NewProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Profile profile = db.profile.Find(id);
            db.profile.Remove(profile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/NewProfiles/Create.cshtml
@model MIS4200_Team8.Models.Profile

@{
    ViewBag.Title = "Create an Employee";
}

<h2>Create a New Employee</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstName,"First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName,"Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnitLocation,"Business Unit", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.businessUnitLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.businessUnitLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hireDate,"Hire Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hireDate, new { htmlAttributes = new { @class = "form-control" } })               
                @Html.ValidationMessageFor(model => model.hireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobTitleName,"Job Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.jobTitleName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.jobTitleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NewProfiles/Delete.cshtml
@model MIS4200_Team8.Models.Profile

@{
    ViewBag.Title = "Delete Employee";
}

<h2>Delete Employee Data</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            First Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            Last Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            Business Unit
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnitLocation)
        </dd>

        <dt>
            Hire Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hireDate)
        </dd>

        <dt>
            Job Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobTitleName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        <div class="alert alert-danger">
            <strong>Danger!</strong> The action of deleting your account is irreversible.
        </div>
        </div>
    }
</div>

Views/NewProfiles/Details.cshtml
@model MIS4200_Team8.Models.Profile

@{
    ViewBag.Title = "Employee Details";
}

<h2>Employee Details</h2>

<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            First Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            Last Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            Business Unit
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnitLocation)
        </dd>

        <dt>
            Hire Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hireDate)
        </dd>

        <dt>
            Job Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobTitleName)
        </dd>

    </dl>
</div>

@*<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.award)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognizor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognitionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descritption)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.award)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.employeeGiving.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.recognitionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descritption)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.recognitionID })

            </td>
        </tr>
    }

</table>*@

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.profileID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/NewProfiles/Edit.cshtml
@model MIS4200_Team8.Models.Profile

@{
    ViewBag.Title = "Edit Employee";
}

<h2>Edit Employee</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
  
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.profileID)

        <div class="form-group">
            @Html.LabelFor(model => model.firstName,"First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName,"Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnitLocation,"Business Unit", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.businessUnitLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.businessUnitLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hireDate,"Hire Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobTitleName,"Job Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.jobTitleName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.jobTitleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NewProfiles/Index.cshtml
@model IEnumerable<MIS4200_Team8.Models.Profile>

@{
    ViewBag.Title = "Employee List";
}

<h2>Employee List</h2>

@*<p>
    @Html.ActionLink("Create New Employee", "Create")
</p>*@

@*<searh class="text-muted">*@
       @using (Html.BeginForm("Index", "NewProfiles", FormMethod.Get))
       {
           <p>
               Find by name: @Html.TextBox("searchString")
               <input type="submit" value="Search" />
           </p>

       }

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Business Unit
        </th>
        <th>
            Hire Date
        </th>
        <th>
            Job Title
        </th>
        <th>
            Total Recognitions
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.firstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.lastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.businessUnitLocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.hireDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.jobTitleName)
    </td>
    <td>
        @{ 
            var totalRecognitions = 0;
            try
            {
                totalRecognitions = item.employeeGetting.Count();
                
            }
            catch (Exception)
            {

                // nothing to catch
            }
            
        }
        @totalRecognitions
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.profileID }) |
        @Html.ActionLink("Details", "Details", new { id = item.profileID })
        @*@Html.ActionLink("Delete", "Delete", new { id = item.profileID })*@
    </td>
</tr>
}

</table>

Views/NewProfiles/notAuthorized.cshtml
@{
    ViewBag.Title = "notAuthorized";
}

<br />
<div class="alert alert-danger">
    <strong>Danger!</strong> You are not authorized to change information that is not your own.
</div>

<br />
@Html.ActionLink("Back to List", "Index")